export { default as RankingPage } from './ranking'
export { default as FuzzyPage } from './fuzzy'
export { default as ExpertQuestionnairePage } from './expertQuestionnaire'
export { default as KnowledgeManagementPage } from './knowledgeManagement'
export { default as PerformancePage } from './performance'
export { default as FormQuestionnaire } from './questionnaireRespondent/form'
export { default as QuestionnairePage } from './questionnaireRespondent'